from io import BytesIO
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph
 
 
def generate_pdf(issue):
    """
    Generate a PDF for the selected DMS issue.
 
    Parameters:
        issue (dict)
 
    Returns:
        BytesIO object
    """
 
    buffer = BytesIO()
 
    doc = SimpleDocTemplate(buffer)
 
    styles = getSampleStyleSheet()
 
    story = []
 
    title = issue.get("error", "Unknown Error")
 
    story.append(Paragraph("<b>RSPL DMS AI Assistant</b>", styles["Title"]))
    story.append(Paragraph("<br/>", styles["Normal"]))
 
    story.append(
        Paragraph(f"<b>Error :</b> {title}", styles["Heading2"])
    )
 
    story.append(Paragraph("<br/>", styles["Normal"]))
 
    story.append(
        Paragraph("<b>Recommended Solution</b>", styles["Heading2"])
    )
 
    steps = issue.get("solution", [])
 
    if not steps:
        story.append(
            Paragraph("No solution available.", styles["BodyText"])
        )
    else:
        for i, step in enumerate(steps, start=1):
            story.append(
                Paragraph(f"{i}. {step}", styles["BodyText"])
            )
 
    story.append(Paragraph("<br/><br/>", styles["Normal"]))
 
    story.append(
        Paragraph(
            "Generated by RSPL DMS AI Assistant",
            styles["Italic"]
        )
    )
 
    doc.build(story)
 
    buffer.seek(0)
 
    return buffer
